name: Update generated files

on:
  push:
    paths:
    - '**.js'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: node scripts/generate-languages.md.js
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update generated files
